---
- hosts: all
  become: yes

  vars_files:
  - vars/default_vars.yml
  - "{{ IIAB_DIR }}/vars/default_vars.yml"

  roles:
#    - { role: 0-init, tags: ['0-init'] }
    - { role: "{{ role_to_run }}", tags: ['run'] }
